##Config file containing information for the pureCN.snakefile

## Tools Path
gatk_path: /mnt/storage/apps/gatk-4.3.0.0/gatk
java: /usr/bin/java
tabix: /usr/bin/tabix
picard_jar: /home/ma1111/tools/picard.jar

## Script Path
purecn_script: /home/ma1111/tools/PureCN/extdata/PureCN.R

## Path to reference files
reference_genome: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/ccle/Homo_sapiens_assembly38.fasta
reference_dict: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/ccle/Homo_sapiens_assembly38.dict
reference_index: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/ccle/Homo_sapiens_assembly38.fasta.fai
intervals: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/ccle/references_intervals_agilent_hg38_lifted_chrXY.no_header.list
common_sites: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/ccle/common_sites_hg38_lifted.list
purecn_intervals: /mnt/storage/labs/sviswanathan/tRCC_data/trcc_wes/ccle/references_PureCN_intervals_wgs_hg38_2_percent_intervals.txt
